data_source capag:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: '#### COLOQUE AQUI O PROJECT ID GERADO PELO GCP ####'
    dataset: capag

soda_cloud:
  host: #### COLOQUE AQUI A INFORMACAO GERADA PELA API KEY DO SODA ####
  api_key_id: #### COLOQUE AQUI A INFORMACAO GERADA PELA API KEY DO SODA ####
  api_key_secret: #### COLOQUE AQUI A INFORMACAO GERADA PELA API KEY DO SODA ####
