version: 2

sources:
  - name: capag
    database: #### COLOQUE AQUI O PROJECT ID GERADO PELO GCP ####
    tables:
      - name: capag_brasil
  
  - name: cidades
    database: #### COLOQUE AQUI O PROJECT ID GERADO PELO GCP ####
    tables:
      - name: cidades_brasil
