capag:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: #### COLOQUE AQUI O PROJECT ID GERADO PELO GCP ####
    dataset: capag
    threads: 1
    timeout_seconds: 800
    location: US
